var icos = [
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 0, 1),
		endDate: new Date(2018, 1, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 1, 1),
		endDate: new Date(2018, 2, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 2, 1),
		endDate: new Date(2018, 3, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 3, 1),
		endDate: new Date(2018, 4, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 4, 1),
		endDate: new Date(2018, 5, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 6, 1),
		endDate: new Date(2018, 7, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 7, 1),
		endDate: new Date(2018, 8, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 8, 1),
		endDate: new Date(2018, 9, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 9, 1),
		endDate: new Date(2018, 10, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 10, 1),
		endDate: new Date(2018, 11, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 11, 1),
		endDate: new Date(2018, 12, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 0, 1),
		endDate: new Date(2018, 1, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 1, 1),
		endDate: new Date(2018, 2, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 2, 1),
		endDate: new Date(2018, 3, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 3, 1),
		endDate: new Date(2018, 4, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 4, 1),
		endDate: new Date(2018, 5, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 6, 1),
		endDate: new Date(2018, 7, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 7, 1),
		endDate: new Date(2018, 8, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 8, 1),
		endDate: new Date(2018, 9, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 9, 1),
		endDate: new Date(2018, 10, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 10, 1),
		endDate: new Date(2018, 11, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 11, 1),
		endDate: new Date(2018, 12, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 0, 1),
		endDate: new Date(2018, 1, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 1, 1),
		endDate: new Date(2018, 2, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 2, 1),
		endDate: new Date(2018, 3, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 3, 1),
		endDate: new Date(2018, 4, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 4, 1),
		endDate: new Date(2018, 5, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 6, 1),
		endDate: new Date(2018, 7, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 7, 1),
		endDate: new Date(2018, 8, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 8, 1),
		endDate: new Date(2018, 9, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 9, 1),
		endDate: new Date(2018, 10, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 10, 1),
		endDate: new Date(2018, 11, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
	{
		name: 'Votem',
		image: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		partnership: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		startDate: new Date(2018, 11, 1),
		endDate: new Date(2018, 12, 1),
		exchangeDate: new Date(),
		description: 'Voting for a mobile world',
	},
];
