var icosRaw = [
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 0, 1),
		EndDate: new Date(2018, 1, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 1, 1),
		EndDate: new Date(2018, 2, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 2, 1),
		EndDate: new Date(2018, 3, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 3, 1),
		EndDate: new Date(2018, 4, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 4, 1),
		EndDate: new Date(2018, 5, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 6, 1),
		EndDate: new Date(2018, 7, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 7, 1),
		EndDate: new Date(2018, 8, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 8, 1),
		EndDate: new Date(2018, 9, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 9, 1),
		EndDate: new Date(2018, 10, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 10, 1),
		EndDate: new Date(2018, 11, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 11, 1),
		EndDate: new Date(2018, 12, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 0, 1),
		EndDate: new Date(2018, 1, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 1, 1),
		EndDate: new Date(2018, 2, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 2, 1),
		EndDate: new Date(2018, 3, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 3, 1),
		EndDate: new Date(2018, 4, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 4, 1),
		EndDate: new Date(2018, 5, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 6, 1),
		EndDate: new Date(2018, 7, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 7, 1),
		EndDate: new Date(2018, 8, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 8, 1),
		EndDate: new Date(2018, 9, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 9, 1),
		EndDate: new Date(2018, 10, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 10, 1),
		EndDate: new Date(2018, 11, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 11, 1),
		EndDate: new Date(2018, 12, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 0, 1),
		EndDate: new Date(2018, 1, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 1, 1),
		EndDate: new Date(2018, 2, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 2, 1),
		EndDate: new Date(2018, 3, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 3, 1),
		EndDate: new Date(2018, 4, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 4, 1),
		EndDate: new Date(2018, 5, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 6, 1),
		EndDate: new Date(2018, 7, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 2,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 7, 1),
		EndDate: new Date(2018, 8, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 1,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 8, 1),
		EndDate: new Date(2018, 9, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 5,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 9, 1),
		EndDate: new Date(2018, 10, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 4,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 10, 1),
		EndDate: new Date(2018, 11, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
	{
		Name: 'Votem',
		ImageUrl: 'https://tokenmarket.net/blockchain-static/ethereum/assets/votem/logo_small.png',
		PartnershipLevel: 3,
		ICOWeb: 'https://www.votem.io/',
		ICOReport: 'https://votem.com/our-story/',
		FXPage: 'https://www.fxstreet.com/',
		StartDate: new Date(2018, 11, 1),
		EndDate: new Date(2018, 12, 1),
		ExchangeDate: new Date(),
		Description: 'Voting for a mobile world',
	},
];
